#!/usr/bin/env python
# Author: Giles Hall
# GIT wrapper that lets you specify your SSH key

import sys
import os
import tempfile
import subprocess

SSH_WRAP = '#!/bin/sh\nssh -T -i %s -o "StrictHostKeyChecking no" $@\nrm %s'
GIT_CMD = "/usr/bin/git"

class SSH_GIT_Wrap(object):
    def do_wrap(self):
        i_idx = None
        self.argv = sys.argv[:]
        self.argv[0] = GIT_CMD
        self.ssh_wrap_fn = None
        for (idx, arg) in enumerate(self.argv):
            if arg == "-i":
                i_idx = idx
                break
        if i_idx == None:
            self.do_wrap = False
            return

        key_fn = self.argv[i_idx + 1]
        del self.argv[i_idx + 1]
        del self.argv[i_idx]
        assert os.path.exists(key_fn)

        (f, fn) = tempfile.mkstemp()
        self.ssh_wrap_fn = fn
        f = os.fdopen(f, 'w')
        f.write(SSH_WRAP % (key_fn, self.ssh_wrap_fn))
        f.close()
        os.chmod(fn, 0700)
        os.environ["GIT_SSH"] = self.ssh_wrap_fn

    def do_git(self):
        self.argv.insert(1, "git")
        print self.argv
        os.execl(*self.argv)

if __name__ == "__main__":
    git_wrapper = SSH_GIT_Wrap()
    git_wrapper.do_wrap()
    git_wrapper.do_git()
